apiVersion: v2
name: hypercontract
description: A Helm chart for hypercontract

type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: app
    alias: hypercontract
    version: 0.0.1
    repository: "file://./charts/app"
  - name: app
    alias: hypershop
    version: 0.0.1
    repository: "file://./charts/app"
  - name: app
    alias: docs
    version: 0.0.1
    repository: "file://./charts/app"
