name: Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  hypercontract:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build and push hypercontract
      uses: docker/build-push-action@v5
      with:
        push: true
        file: ./Dockerfile.hypercontract
        tags: |
          hypercontract/hypercontract:latest
          hypercontract/hypercontract:${{ github.sha }}

  hypershop:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build and push hypershop
      uses: docker/build-push-action@v5
      with:
        push: true
        file: ./Dockerfile.hypershop
        tags: |
          hypercontract/hypershop:latest
          hypercontract/hypershop:${{ github.sha }}

  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build and push docs
      uses: docker/build-push-action@v5
      with:
        push: true
        file: ./Dockerfile.docs
        tags: |
          hypercontract/docs:latest
          hypercontract/docs:${{ github.sha }}
